[package]
name = "rust_pdfme"
version = "0.1.0"
edition = "2021"

[dependencies]
allsorts = "0.15.0"
derive-new = "0.7.0"
icu_segmenter = { version = "1.5.0", features = ["serde"] }
palette = "0.7.6"
printpdf = { git = "https://github.com/fschutt/printpdf", features = ["bmp", "png"] }
qrcode-generator = "5.0.0"
serde = { version = "1.0.217", features = ["derive", "serde_derive"] }
serde_json = "1.0.139"
snafu = "0.8.5"
